### PR TITLE
Add k8s manifests and custom values

### PR DESCRIPTION
**Pull request by cuttingedge1109**
### What's in it?
- [x] Customized version of [Synapse Helm Chart](https://gitlab.com/ananace/charts/-/tree/master/charts/matrix-synapse) for our use case
- [x] Add values.yaml file for our synapse configuration (https://github.com/cilicon/skytalk/wiki/Matrix-server-installation)
- [x] Used our Synapse container image

This is running on signal k8s cluster now.

### CODE REVIEW

**Comment by cuttingedge1109** [comment]
### TODO
- [x] Define the branch rule for this forked repository.
Now I added the github action to build and push our synapse image so we have `ciliconherve/synapse:latest`. This image was built from `login_3pid` branch because [matrix install guide](https://github.com/cilicon/skytalk/wiki/Matrix-server-installation) is using that branch. Is this the main branch of our synapse? 
Once the main branch is adopted, need to protect that using branch rule to avoid direct push commits which is rebuilding the container image.
- [x] Decide how to manage synapse helm chart manifests. 
In this PR, I created `k8s` dir and put the helm chart manifests in it. It is customized from the [upstream repo](https://gitlab.com/ananace/charts/-/tree/master/charts/matrix-synapse). A new dedicated repo or just keep here?
Btw, that upstream repo is a personal one in gitlab so we need to have our version separately.

- [x] Once the main branch is selected and branch rule is defined, add auto deployment github action to the k8s cluster. Now it is running on signal cluster but installed manually.

**Comment by hervejegou** [comment]
@cuttingedge1109  maybe it is better to run all matrix instances in a separate K8 cluster, not mixed up with our signal cluster which is for our signal servers and will scale up.
We can create 'matrix' cluster in our SKYTALK project for this ?

**Comment by cuttingedge1109** [comment]
> 
> 
> @cuttingedge1109 maybe it is better to run all matrix instances in a separate K8 cluster, not mixed up with our signal cluster which is for our signal servers and will scale up.
> We can create 'matrix' cluster in our SKYTALK project for this ?

**Comment by cuttingedge1109** [comment]
> 
> 
> @cuttingedge1109 maybe it is better to run all matrix instances in a separate K8 cluster, not mixed up with our signal cluster which is for our signal servers and will scale up.
> We can create 'matrix' cluster in our SKYTALK project for this ?

Ok, I will try.
Also we can create clusters per project, like dev cluster(signal, matrix will run on one cluster for dev), startchat, main ...

**Comment by cuttingedge1109** [comment]
Created a dedicated repo for helm chart https://github.com/cilicon/helm-charts

**Pull request closed without merging**
